name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    environment: github-pages
    
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        echo "REACT_APP_BEARER_TOKEN=${{ secrets.REACT_APP_BEARER_TOKEN }}" >> $GITHUB_ENV
        npm install
        REACT_APP_BEARER_TOKEN=${{ secrets.REACT_APP_BEARER_TOKEN }} npm run-script build
      env:
        CI: true
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
