name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    environment: github-pages
    
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        echo "REACT_APP_BEARER_TOKEN=${{ secrets.REACT_APP_BEARER_TOKEN }}" >> $GITHUB_ENV
        npm install
        npm run-script build
      env:
        CI: false
        REACT_APP_BEARER_TOKEN: ${{ env.REACT_APP_BEARER_TOKEN }}
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
